//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AsyModbus.Pages
{
    public partial class ParametreIslemleri
    {
        protected global::System.Web.UI.WebControls.DropDownList ddlParametreGruplari;
        protected global::System.Web.UI.WebControls.Panel pnlParametreBolumu;
        protected global::System.Web.UI.WebControls.DropDownList ddlParametreler;
        protected global::System.Web.UI.WebControls.TextBox txtParametreId;
        protected global::System.Web.UI.WebControls.TextBox txtParametreKod;
        protected global::System.Web.UI.WebControls.TextBox txtParametreAd;
        protected global::System.Web.UI.WebControls.TextBox txtParametreAciklama;
        protected global::System.Web.UI.WebControls.Button btnParametreEkle;
        protected global::System.Web.UI.WebControls.Button btnParametreGuncelle;
        protected global::System.Web.UI.WebControls.Button btnParametreSil;
        protected global::System.Web.UI.WebControls.Panel pnlGrupAlanlari;
        protected global::System.Web.UI.WebControls.TextBox txtGrupId;
        protected global::System.Web.UI.WebControls.TextBox txtGrupKod;
        protected global::System.Web.UI.WebControls.TextBox txtGrupAd;
        protected global::System.Web.UI.WebControls.TextBox txtGrupAciklama;
        protected global::System.Web.UI.WebControls.Button btnGrupEkle;
        protected global::System.Web.UI.WebControls.Button btnGrupGuncelle;
        protected global::System.Web.UI.WebControls.Button btnGrupSil;
    }
}
